# Generated by Django 5.0.4 on 2024-04-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('telegram_id', models.CharField(max_length=32)),
                ('key_word', models.CharField(blank=True, max_length=16, null=True)),
                ('key_gaven_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
