# Generated by Django 5.0.4 on 2024-04-10 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xitoy_cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partiya_name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('arrived_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=16)),
                ('key_gaven_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trek_code', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='key_gaven_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='key_word',
        ),
        migrations.AddField(
            model_name='client',
            name='kalit_soz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xitoy_cargo.key'),
        ),
        migrations.CreateModel(
            name='Chine_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('count_of_product', models.IntegerField(null=True)),
                ('massa_of_product', models.FloatField()),
                ('karopka_nomi', models.CharField(max_length=64)),
                ('accepted_date', models.DateField(auto_now_add=True)),
                ('id_raqam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xitoy_cargo.client')),
                ('partiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xitoy_cargo.available_party')),
                ('trek_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xitoy_cargo.trek')),
            ],
        ),
        migrations.CreateModel(
            name='Uzbek_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TOLANGAN', "To'langan"), ("TO'LANMAGAN", "To'lanmagan")], default='TOLANGAN', max_length=16)),
                ('massa_of_product', models.IntegerField()),
                ('price_for_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('accepted_date', models.DateField(auto_now_add=True)),
                ('id_raqam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xitoy_cargo.client')),
                ('partiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xitoy_cargo.available_party')),
                ('trek_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xitoy_cargo.trek')),
            ],
        ),
    ]
