# Generated by Django 4.2.11 on 2024-04-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xitoy_cargo', '0003_alter_available_party_arrived_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
